
name = "aikenprojects/paymentchannels"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aikenprojects/paymentchannels'"

[repository]

user = "aikenprojects"
project = "paymentchannels"
name = "amy/payment_channel"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'amy/payment_channel'"

[repository]

user = "amy"
project = "payment_channel"
platform = "github"

[[dependencies]]

name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
