name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
<<<<<<< HEAD
          version: v1.1.4
=======
          version: v1.1.7
>>>>>>> c28f397 (Payment channel code)
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
